version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "SPHINX_APIDOC_OPTIONS=members,show-inheritance sphinx-apidoc -f -d 0 -o docs/source ./"
      - "jupyter-book config sphinx ./"


python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .

formats:
  - pdf
  - epub
